### ISSUE TITLE
整理offline的repo

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#13]
@leo424y 麻煩你 DNS猶未好進前先做～
- travis ci的deploy GITHUB_TOKEN
- README badge

https://github.com/twgo/gu2-im1_pian7-sik4_offline

**Comment by leo424y** [comment]
http://asr-offline.iis.sinica.edu.tw/ 已上線囉！badge也已更新

**Comment by leo424y** [comment]
隊長居然邊開會就把秒數限制解決，帥啊啊!
