### ISSUE TITLE
辨識失敗

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#14]
USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
root      20   0 9370704 3.315g    264 D  33.9 86.0   2:51.80 lattice-lmresco

![2018-06-01 11-39-36](https://user-images.githubusercontent.com/5996555/40820014-97529b4a-6590-11e8-8de2-44f416256550.png)

**Comment by sih4sing5hong5** [comment]
是因為記憶體無夠，毋過無法度閣加矣
![2018-06-01 11-36-00](https://user-images.githubusercontent.com/5996555/40819988-6cc7fe6a-6590-11e8-8244-166d42d96941.png)

@leo424y exp的彼臺vm，敢會當放一寡仔記憶體出來？
asr彼台加到16G記憶體

**Comment by leo424y** [comment]
已從dl移ram，降至2，目前它沒在用。
asr ram已升至16，未來要再加的話，我來聯絡資訊室再開特殊規格。

```
tl@tl:~$ free
              total        used        free      shared  buff/cache   available
Mem:       16428836      155272    15983816        8920      289748    15992252
Swap:      10383352           0    10383352
```
