### ISSUE TITLE
改前端程式

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#2]
要求
- 佇這个專案改
- 親像master，錄音了，直接上傳
- 親像「拆錄音辨識兩頁」bracnh，錄音一擺，擲三个語言的post出去
- 會當用舊的後端試

# REF
- 4/25  試讀code  
- https://github.com/danrouse/react-audio-recorder
- https://github.com/hackingbeauty/react-mic

**Comment by sih4sing5hong5** [comment]
我的後端主機欲自linode徙去digital ocean
這馬`服務.意傳.台灣`已經指去`digital ocean`
我用`舊服務.意傳.台灣`繼續指舊的`linode`主機

想欲問你這兩工敢有按算排時間改前端
若是欲試我就留linode，無我就愛關掉省錢矣～～

**Comment by leo424y** [comment]
可以先關，我還在理解前端程式，需要一點時間才能改，謝謝大隊長給機會練功。

**Comment by sih4sing5hong5** [comment]
關矣

**Comment by leo424y** [comment]
master 與 branch 是兩種寫法，抱歉，我暫時先投降！

**Comment by sih4sing5hong5** [comment]
好
