### ISSUE TITLE
向資訊室改domain name GitHub io

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#3]
`asr.iis.sinica.edu.tw`應該用cname指向`twgo.github.io`
進前申請毋著
愛去資訊室重申請

`IP,Name或機房空間申請、IP,Name 或機房空間資料異動`

# log 
- 4/25 申請 `asr.iis.sinica.edu.tw`應該用cname指向`twgo.github.io`
- 5/7 2018-05-07 08:33:22.271 | 資訊室檢查 | PI審核 . XDDDD 也太久

**Comment by leo424y** [comment]
http://asr.iis.sinica.edu.tw 已指過去囉

**Comment by sih4sing5hong5** [comment]
好，這兩工我來處理
