### ISSUE TITLE
自動deploy master到 gh-page

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#4]
https://github.com/i3thuan5/tau3_phah4-ji7/blob/master/.travis.yml#L17-L25

# REF
- https://juejin.im/post/5adb48b3f265da0ba76f502a
- https://docs.travis-ci.com/user/deployment/pages/
- secure issue https://github.com/i3thuan5/tau3_phah4-ji7/blob/3602e67dee33b4e0ecb37dd2ee724f14bd1c8203/.travis.yml#L23

**Comment by leo424y** [comment]
https://github.com/twgo/gu2-im1_pian7-sik4/blob/7bf5c29638d6641438f1f5e09d23defacb59148e/.travis.yml#L15
