### ISSUE TITLE
kaldi=>dockerhub

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/gu2-im1_pian7-sik4#5]
共 https://github.com/kaldi-asr/kaldi/tree/master/misc/docker/ubuntu 擲到dockerhub面頂，以後咱就用copy的就好

咱家己的kaldi repo嘛會當囥去dockerhub，佇dockerhub做兩个repo
```
RUN git clone https://github.com/sih4sing5hong5/kaldi.git
```

# REF
- 4/25 發佈：docker - kaldi 官版、sih4sing5hong5版

**Comment by sih4sing5hong5** [comment]
dockerfile你敢有留？
抑是你只是改kaldi/misc/ubuntu的clone path？

**Comment by sih4sing5hong5** [comment]
https://hub.docker.com/r/gotw/kaldi-ihc/
https://hub.docker.com/r/gotw/kaldi-origin/

**Comment by leo424y** [comment]
dockerfile 用 kaldi/misc/ubuntu的
但這才發現裡頭的 clone path 不是你的repo
難怪build完是一樣的
已改 clone path，正在重build中
完成後重push通知你

**Comment by leo424y** [comment]
正確的 kaldi-ihc 推囉 https://hub.docker.com/r/gotw/kaldi-ihc/
